### ISSUE TITLE
"Import Extensions" does not work on VS2019.RC

### ISSUE THREAD

**Issue by schuettecarsten** [loop8ack/ExtensionPackTools#16]
I have exported my extensions from VS2019.Preview and tried to import the file to VS2019.RC1.SVC1. I can see "Downloading Extensions" and "Extensions downloaded. Starting VSIX Installer..." in status bar, but then noting happens. No progress indicator, no VSIX Installer, nothing. After some minutes, status bar shows "Ready.". Restart VS2019, but no new extensions appear.

**Comment by madskristensen** [comment]
Fixed

**Comment by KexyBiscuit** [comment]
It seems that the problem is back? Visual Studio 2019 version 16.2 Preview 1.

**Comment by KexyBiscuit** [comment]
@madskristensen The symptom is nearly identical, do I have to create a new issue?

**Comment by KexyBiscuit** [comment]
Version 16.2.0 Preview 3.0 no longer has the problem. Strange.
